SUPERNET:
  MLP_RATIO: 4.0
  NUM_HEADS: 12
  EMBED_DIM: 768
  DEPTH: 12
SEARCH_SPACE:
  MLP_RATIO:
    # - 3.0
    # - 3.5
    - 4.0
  NUM_HEADS:
    # - 10
  # - 11
    - 12
  DEPTH:
    # - 10
    # - 11
    - 12
  EMBED_DIM:
    # - 640
    # - 704
    - 768
